version: "3"

services:
  keycloak: 
    image: quay.io/keycloak/keycloak:12.0.1
    container_name: keycloak
    restart: always
    environment: 
      KEYCLOAK_USER: "nimdadod"
      KEYCLOAK_PASSWORD: "secret"
    ports: 
      - "8080:8080"
  webby: 
    build: app/.
    container_name: webby
    ports: 
      - "8081:8081"
    
